### ISSUE TITLE
unveil function should check if data-src attribute exists

### ISSUE THREAD

**Issue by kenyee** [luis-almeida/unveil#1]
I'm using Meteor that refreshes parts of the page automatically and when unveil() is called multiple times, it blanks out the images because it doesn't check if the data-src attribute exists already.  It needed a 2 line change:
        this.one( "unveil", function(){
            source = this.getAttribute( "data-src" );
+++     if (source != null) {
          this.setAttribute( "src", source );
          this.removeAttribute( "data-src" );
+++     }
        } );

p.s. thanks for this plugin.  The lazyload plugin was really flaky (needed you to move the scrollbar before the first page of images displayed) so it was unusable for me :-(

**Comment by luis-almeida** [comment]
@kenyee this has been added to the script already.
Sorry for taking So Long to reply btw.

**Comment by seandelaney** [comment]
Current version only supports `data-src` attribute. If an img doesn't have `data-src`.eg images added via RTE, they are not lazy loaded.
