### ISSUE TITLE
abandoned?

### ISSUE THREAD

**Issue by huglester** [luis-almeida/unveil#106]
Hello,

is this abandoned? @luis-almeida

**Comment by hongaar** [comment]
Cross posted from #61:

> There are several forks and useful PR's at the moment. What about joining forces to discuss what we can do to help push this repository to a next version?

I created and just updated [unveil2](http://nabble.github.io/unveil2/), would be great to merge back and work on this together.

**Comment by hongaar** [comment]
Let's continue the work on this plugin, even eBay is using some modified version of this plugin :smile: 
@luis-almeida ?

![image](https://cloud.githubusercontent.com/assets/205834/14349754/8aed5f56-fcc5-11e5-80b4-b973855dd165.png)

**Comment by huglester** [comment]
this: https://github.com/nabble/unveil2
