### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by feliperohdee** [luis-almeida/unveil#11]
Hi, that library is compatible with all major browser? And IE8 and IE9?

**Comment by jakerocheleau** [comment]
I don't have IE8 installed but I had no problems with IE9. Firefox, Opera, Chrome, and Safari also work perfectly for me.

**Comment by fiedomedia** [comment]
I've tested it with IE 7, 8, 9 and 10, on Win7 and Win8, all worked like a charm.

**Comment by feliperohdee** [comment]
Thank guys!

**Comment by luis-almeida** [comment]
I updated the documentation so I'm closing this issue.

Thanks guys!
