### ISSUE TITLE
Failed to execute 'webkitMatchesSelector' on 'Element': ':hidden' is not a valid selector

### ISSUE THREAD

**Issue by rainbow57** [luis-almeida/unveil#114]
I use unveil and zepto(version: 1.1.6), and got the error:
Uncaught SyntaxError: Failed to execute 'webkitMatchesSelector' on 'Element': ':hidden' is not a valid selector.

This error is caused by the code "is(':hidden')" in the 34 line.
Is there any way to fix it ?

**Comment by rainbow57** [comment]
Duplicate of #51

**Comment by jtrolle** [comment]
Check [Zepto Modules](https://github.com/madrobby/zepto#zepto-modules) and add the modules that you need.

You must add at least selector.js, you can build your version with the [builder](http://github.e-sites.nl/zeptobuilder/)
