### ISSUE TITLE
Add .class after loading image

### ISSUE THREAD

**Issue by sarceda** [luis-almeida/unveil#13]
Woult it be possible to add a .class to te image after it was loaded?

**Comment by luis-almeida** [comment]
@sarceda, can you you give me an use case?

**Comment by luis-almeida** [comment]
I'll mark this one as a duplicate from https://github.com/luis-almeida/unveil/issues/24 since adding a callback would allow that.

**Comment by ultrono** [comment]
FYI, to add a "loaded" class:

```
$('img').unveil(200, function() {
   $(this).on('load', function () {
      this.classList += ' lazy-loaded'
   })
})
```
