### ISSUE TITLE
When refreshing from halfway down page, unveil doesn't reveal unless page is scrolled up

### ISSUE THREAD

**Issue by perry-garvin** [luis-almeida/unveil#144]
Hi there,

I like Unveil a lot. Strangely in Chrome when refreshing the page from halfway down the page, Unveil doesn't reveal unless page is scrolled up. I made video explaining here:

https://www.dropbox.com/s/7edhh7npbaus4p8/Unveil.mov?dl=0

**Comment by ZLevine** [comment]
@the-magus do you have any other JS on the page using the scroll event? I've found that these can sometimes delay or block unveiling, depending on what they're doing.

**Comment by perry-garvin** [comment]
Hi Zach - thanks for following up. That may be the case. At any rate, I decided to try another approach with another loader. I do like Unveil's minimal nature, though!
