### ISSUE TITLE
Question about compatibility with other jQ plugins

### ISSUE THREAD

**Issue by chimericdream** [luis-almeida/unveil#17]
Does this only work when a user scrolls to an image? I have a very large table that is split using jQuery Data Tables into multiple pages. I'd prefer to lazy load the images only when the "page" containing the images is visible.

Thanks.

**Comment by luis-almeida** [comment]
As it is now, yes! You have to scroll to the image to `unveil` it.

But you have a workaround if you're working with paginated tables or tabs for instance:
1.  Do not apply unveil to all the images just to the visible ones: `$("#container img:visible").unveil()`.
2.  Whenever a user opens a different page or tab, just apply the plugin again: `$("#container img:visible").unveil()`.
