### ISSUE TITLE
mobile chrome (data-src, src)

### ISSUE THREAD

**Issue by Krknv** [luis-almeida/unveil#23]
galaxy note, chrome. 
work only if data-src is before src

**Comment by luis-almeida** [comment]
Nice catch! Thanks a lot for the heads up!
I have written some tests (still not in master) and will soon add CI and integrate with sauce labs so we can catch more bugs like this one.

**Comment by bridgeport** [comment]
Are you both talking about the attribute order in the HTML source?

So the following fails:

```
<img src="blank.gif" data-src="realimage.jpg">
```

but the following works?

```
<img data-src="realimage.jpg" src="blank.gif">
```

If so, do we just need to change the attribute order in the HTML for the time being?

**Comment by Krknv** [comment]
yes
