### ISSUE TITLE
Add a call back function

### ISSUE THREAD

**Issue by ktoumaniac** [luis-almeida/unveil#24]
Hello!

First, thanks a lot for your work, this plugin is really nice and the code pretty clear!!

So I wanted to know if you expect to add a call back to Unveil? Something like:
    $("img").unveil(200, function(){
        //alert()<image loaded
    });

What I have in made is to be able to add a fade effect, or animate...

**Comment by luis-almeida** [comment]
Hey, Thanks for your feedback!
The main goal of the plugin is to be really small, focusing primarily on lazy loading and leaving fancy features out.
Having said that, I'm considering adding this feature but only if enough people up-vote it in this thread.

**Comment by milindalvares** [comment]
:+1: 

How much weight would a callback function add to the plugin? Also, is there any easy way an end user can add such a function to the plugin, like maybe a module? I know I'm asking too much.

**Comment by luis-almeida** [comment]
It's not about the weight it adds since that's neglectable . It's about being as minimal in features as possible.
I'm just asking for feedback from people first to understand if that is something that they'll use because I won't.

Currently the only way is to fork the code and add the callback.

**Comment by hendrasan** [comment]
It's probably useful for example for images with caption, to display caption only if the image has been loaded.

**Comment by neverything** [comment]
This is indeed a fantastic plugin! The callback would be much appreciated as for images that are set in CSS to height: auto; (RWD) it would be very helpful to have a callback to say, for example when the image is loaded set the height to auto and not before.

**Comment by milindalvares** [comment]
Yup, that's the reason I'd like a callback. To call masonry every time an image loads.

**Comment by luis-almeida** [comment]
Thanks for your feedback everyone!
I just added the callback option and also documentation on how to use it to add an entrance animation.
