### ISSUE TITLE
adaptive images

### ISSUE THREAD

**Issue by desmedtk** [luis-almeida/unveil#26]
Thanks a lot for your work!

I'm trying to get this to work with Adaptive Images (http://adaptive-images.com/).
Result: the images are resized correctly, but they don't lazy load any more.

Any ideas how to fix this? (I want to use it on a page with a lot of pictures, so I definitely need to lazy load them.)

**Comment by desmedtk** [comment]
My bad, the placement of the images was the problem (all above the fold). But, for those of you interested: it works perfectly with adaptive images. So with these two combined, you can lazy load adaptive images! :)

**Comment by petripottonen** [comment]
Hello desmedtk!

Can ask what kind of solution did you use? Which lazyload plugin etc?
Thanks!

**Comment by desmedtk** [comment]
I used Adaptive Images (http://adaptive-images.com/) and Unveil (https://github.com/luis-almeida/unveil).

Regards,
Ken
