### ISSUE TITLE
Not working with Quicksand.js?

### ISSUE THREAD

**Issue by mikeselander** [luis-almeida/unveil#27]
I have a sortable portfolio where I'm trying to integrate unveil.js and I'm having issues with the sorting part of the situation.

Unveil works awesome (LOVE the lightweight functionality) when simply loading the page, however when you sort by any of the parameters it screws with the lazy-loading. Any thoughts on how to fix this?

For reference I'm using Quicksand 1.2.2, Easing 1.3, and a script to bring it together that can be found here: http://www.oldtownmediainc.com/wp-content/themes/otm/js/script.js

Here is my testing page: 
http://www.oldtownmediainc.com/testing-unveil-page/

Thanks you in advance for any help!

**Comment by luis-almeida** [comment]
That was because unveil was filtering all the images and not just the visible ones.
This should now be fixed in v1.3.0.
