### ISSUE TITLE
Make unveil.js even more awesome

### ISSUE THREAD

**Issue by nicovanzyl** [luis-almeida/unveil#29]
Now this is just an idea but what if instead of a spinner while images are loading we have this (https://github.com/rstacruz/nprogress) I think it's a great use for the progress bar. BTW love the simplicity of unveil ;)

**Comment by luis-almeida** [comment]
Nprogress monitors the loading of the entire page.
Unveil is about delaying the loading of images individually.
I don't think both concepts work together but if you find way please share :)
