### ISSUE TITLE
v1.2 breaks when callback param is not passed in

### ISSUE THREAD

**Issue by nathanwdavis** [luis-almeida/unveil#33]
Following the discussion about the need for a callback, it seems that it was intended to be an optional thing. I think it would be pretty easy to check that callback exists and is a function before calling it. Something like:

```
if (typeof(v) == "function") {
    callback.call(this);
} 
```

...should do the trick. I would just do a PR myself, but it appears tag 1.2.0 isn't even off master, so might be easier to just do this yourself in your futures branch or whatever.

Also, FYI... I encountered this because bowers now pointed at 1.2.0 as current.

**Comment by luis-almeida** [comment]
Thanks for spotting this! 
It was due to me experimenting on this project at 2am, committing and tagging shit code that wasn't completely reverted as I intended to.
I just pushed a proper v1.2.0 with a working callback and proper documentation.
I'm sorry for any inconvenience I might have caused.
