### ISSUE TITLE
Demo images 6, 7 and 10 not loading on iphone 5 with iOS6 and 7

### ISSUE THREAD

**Issue by o-l-e** [luis-almeida/unveil#34]
On the demo site, i can't seem to load images 6, 7 and 10 on ios6 and 7.

I tried the demo before and after i recently upgraded to ios7, both safari, and was disappointed that these images didn't load. I really like this script, and would love to use it, but i need to know that it will work.

All i get are "missing src" squares on these images.

Anyone else have this issue?

Ps: I have a very good internet connection, so that can't be the reason.

**Comment by mjau-mjau** [comment]
works here iOS7. Perhaps a glitch in the matrix?

**Comment by luis-almeida** [comment]
Hi,

That wasn't a problem with the script but with the documentation.
A high-res image was missing and two other src paths were incorrect. That's why these images weren't being loaded in retina devices.
Thanks for spotting this! It should be fixed now.

**Comment by o-l-e** [comment]
Thank you @luis-almeida, it works now :)
