### ISSUE TITLE
noscript part

### ISSUE THREAD

**Issue by macik** [luis-almeida/unveil#5]
Is it right?

```
<noscript>
  <img src="bg.png" data-src="img1.jpg" />
</noscript> 
```

As I mention it loads `bg.png` instead of actual `img1.jpg`.

**Comment by bsdonaldson** [comment]
To use the no script tag, you'll have to duplicate your code as such. Since the javascript is disabled you'll have to use the actual src for the no script version.

``` html
<noscript>
    <img src="img1.jpg" />
</noscript>
```

So the final code would look something like this

``` html
<img src="bg.png" data-src="img1.jpg" />

<noscript>
    <img src="img1.jpg" />
</noscript>
```

**Comment by luis-almeida** [comment]
What @BrianSDonaldson said is correct.
There was an error in the documentation but it has been fixed already. 
Sorry for that!
