### ISSUE TITLE
Not Working if Data-Src set dynamically

### ISSUE THREAD

**Issue by DSigmund** [luis-almeida/unveil#59]
I am trying to implement unveil on every page in my website.
So i just write the src of all images on page load in the img-data-src. 

See here:
http://jsfiddle.net/g5JxF/

Thanks for your very nice plugin :-)

**Comment by luis-almeida** [comment]
Works for me: [http://jsfiddle.net/g5JxF/3/](http://jsfiddle.net/g5JxF/3/)

Set the `data-src` attribute using jQuery's `.attr` method instead of `.data` which doesn't actually changes the `data-src` attribute.

Also, if your images are within the viewport, they'll be unveiled right away.

**Comment by DSigmund** [comment]
Thanks for the quick and easy answer :-) :+1:
