### ISSUE TITLE
best practice for unveil + retina + responsive?

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [luis-almeida/unveil#71]
Hi!

What would be a simple solution to serve unveil two different data-src-retina-paths? One for a mobile screen size and one for the desktop?

I think it's a common use case but i don't have any idea how to solve it. And I didn't found any well documented solution, so i would be happy if someone will add a solution here :)

**Comment by revelt** [comment]
Hi

I came across this post looking for the same. What we're asking for is by magnitude more complex - it's not simple 1) retina detection + 2) element position on screen query. It's now extra 3) image container's size. And 3. is changing from one image to another...

Although should be doable. Just more attributes and more JS weight..

**Comment by AWqxKAWERbXo** [comment]
It's not about adding more complexity, modern browsers already understand the picture element and media queries. See also: <picture> element (with img-tag as a fallback). The browser will decide, which image would fit best but atm, there is no possibility to add those additional tags/attributes.

I'm just not a programmer, so I can't go for a PR.

**Comment by AWqxKAWERbXo** [comment]
(Can't edit my post on mobile, I wrote: “See also: picture-Element)
