### ISSUE TITLE
Add to Bower.io?

### ISSUE THREAD

**Issue by jperasmus** [luis-almeida/unveil#73]
Hey man,

First off, shot for this cool plugin, just what I normally need for basic lazy loading.

Just a friendly question to ask whether it would be possible for you to add this to Bower.io, so it's easier to include it in projects?

**Comment by OndraM** [comment]
Have you tried http://bower.io/search/?q=unveil ?

**Comment by jperasmus** [comment]
I'm sorry, my bad, I'm pretty sure I tried this earlier, but no harm done.

Thanks for the follow up.
